linters-settings:
  lll:
    line-length: 130
linters:
  enable-all: true
  disable:
    - depguard
    - exhaustive
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - gochecknoglobals
    - gomoddirectives
    - mnd
    - nilnil
    - paralleltest
    - predeclared
    - rowserrcheck
    - tenv
    - testpackage
    - varnamelen
    - wastedassign
    - wrapcheck
